### ISSUE TITLE
Make sure $path variables are dynamically not static   

### ISSUE THREAD

**Issue by MCM-Mike** [MCM-Mike/nfc_db_inventory_cli#1]
in file: https://github.com/MCM-Mike/nfc_db_inventory_cli/blob/master/py2_nfcdbi/bin/activate
VIRTUAL_ENV="..."

please choose a dynamic path not a fix path in reference to the root directory.

**Comment by glihm** [comment]
Hello @MCM-Mike ! I do apologize I just did not check github for a while.. x)
If you still on the project, I can udpate the file, but you surely already modified it.

Thanks!

**Comment by glihm** [comment]
Ready @MCM-Mike ,

you can now activate the virtual env from anywhere:

`source path/py2_nfcdbi/bin/activate <venv_path>`

If something is not working, feel free to comment it. If it's works well, I let you close the issue. :+1:
